### ISSUE TITLE
OBO example doesn't work properly

### ISSUE THREAD

**Issue by cccs-cat001** [Azure-Samples/azure-spring-boot-samples#36] opened 2021-08-23 15:42 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. Complete the example found [here](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/aad/azure-spring-boot-starter-active-directory/aad-resource-server-obo), I did the bare minimum and just did the graph access. Don't worry about the other resource server examples in the properties file.
2. With a token that is valid for your resource server, run [these two example calls](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/aad/azure-spring-boot-starter-active-directory/aad-resource-server-obo#access-the-web-api-a), you'll notice that the `call-graph` endpoint works fine, but the `call-graph-with-repository` fails. 

### Any log messages given by the failure
> no logs are outputted, just a 401 response.

### Expected/desired behavior
> I'd expect the `call-graph-with-repository` endpoint to act the same as the `call-graph` endpoint. 

### OS and Version?
> Ubuntu 20.04

### Versions
> azure-spring-boot-starter-active-directory version 3.7.0

### Mention any other details that might be useful
It has something to do with this line [here](https://github.com/Azure-Samples/azure-spring-boot-samples/blob/main/aad/azure-spring-boot-starter-active-directory/aad-resource-server-obo/src/main/java/com/azure/spring/sample/aad/controller/SampleController.java#L53-L54), as `graph` always ends up null. I've debugged through a bit and I think it's because it's using the wrong repository to get the authorized clients. 
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by backwind1233** [comment] 2021-08-24 09:08
Hi @chenrujun, please take a look at this issue.

**Comment by cccs-cat001** [comment] 2021-08-24 17:37
I think I've found a solution, whether it's actually correct or not, it works for me, here's what I've changed: 
```diff
public String callGraphWithRepository(HttpServletRequest servletRequest, HttpServletResponse servletResponse) {
         Authentication principal = SecurityContextHolder.getContext().getAuthentication();
-       RequestAttributes requestAttributes = RequestContextHolder.currentRequestAttributes();
-       ServletRequestAttributes sra = (ServletRequestAttributes) requestAttributes;
-       OAuth2AuthorizedClient graph = oAuth2AuthorizedClientRepository
-           .loadAuthorizedClient("graph", principal, sra.getRequest());
+    	OAuth2AuthorizeRequest authorizeRequest = OAuth2AuthorizeRequest
+				.withClientRegistrationId("graph")
+				.principal(principal)
+				.attribute(HttpServletRequest.class.getName(), servletRequest)
+				.attribute(HttpServletResponse.class.getName(), servletResponse)
+				.build();
+   	OAuth2AuthorizedClient graph = this.authorizedClientManager.authorize(authorizeRequest);
        return callMicrosoftGraphMeEndpoint(graph);
    }
```

As well as this change to the class variables:
```diff
@Autowired
-private OAuth2AuthorizedClientRepository oAuth2AuthorizedClientRepository;
+private OAuth2AuthorizedClientManager authorizedClientManager;
```

**Comment by cccs-cat001** [comment] 2021-08-24 18:03
With a bit more experimenting it looks like the two `attribute` lines adding in the request/response can go too. Not sure what the purpose of those were.

**Comment by chenrujun** [comment] 2021-09-05 23:45
Hi, @zhichengliu12581 , could you please assign this issue to you?

**Comment by zhichengliu12581** [comment] 2021-09-08 06:39
Hi, @cccs-cat001
This problem is caused by Spring's inability to recognize the custom `AuthorizationGrantType`, and it has been fixed in this [pr](https://github.com/Azure/azure-sdk-for-java/pull/23366). 
**3.8.0** is now available, you can try to upgrade the **azure-spring-boot-starter-active-directory**. 

The solution you gave is feasible, it will execute obo flow again.
But if you have accessed the `call-graph`, the client will be cached in `OAuth2AuthorizedClientRepository`. In this way, when you try to get a client named `graph`, the cached data will be used first (if you have not visited the `call-graph`, there is no cached data, then the load will fail). In this way, you do not need to request a new token again.

**Comment by zhichengliu12581** [comment] 2021-09-26 10:47
Close this issue because there is no further reply, if you have other questions, please reopen this issue.

**Closed by zhichengliu12581** 2021-09-26 10:47 UTC
Labels: azure-spring
